spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_test?serverTimezone=GMT%2B8
    username: root
    password: a
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
